### ISSUE TITLE
Using PlatformIO with the Code from this github

### ISSUE THREAD

**Issue by tadder** [RalphBacon/205-Internet-Radio#11]
I am attempting to get to grips with platformio. I have successfully compiled and loaded to a TTGO T8 a blink sketch. But so far no luck with the Web Radio Sketch.

In the Sketch folder you have a README.md file that states:
### For PlatformIO
This is the complete project, you know what to do to include it into your workspace. (Note, you may need to edit your workspace folder at the same level as your Project's folder) to something like this:
```
"folders": [
		{
			"name": "ESP32 Better Internet Radio",
			"path": "Projects\\ESP32 Better Internet Radio"
		}
	],
  ```
  It will then appear in PlatformIO's workspace list of projects.

When I attempt to compile it throws up a number of ‘include’ errors and I suspect it may be something to do with ‘levels’ Can you explain what you mean by the above please?
Maybe I need to get up to speed with vcpkg package manager?

**Comment by RalphBacon** [comment]
If you find my email address in the about tab of my channel here: https://www.youtube.com/c/RalphBacon/about and click on the Show Email Address button (this won't work using a phone BTW) then we can communicate via email.

I've just created a new VM running Window 10 so I can (eventually) show Arduinites how to install PlatformIO (for this project, ostensibly, but it will apply for all uses) and all the things I did to get it to work so wonderfully well!
