### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by pipikupi** [RalphBacon/205-Internet-Radio#12]
hi
durring compilation had some errors how can I deal with it ?
Thanks indeed

In file included from C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\main.h:40:0,
                 from C:\Users\user\Documents\Arduino\ESP32-WROVER_Web_Radio\ESP32-WROVER_Web_Radio.ino:2:
C:\Users\user\Documents\Arduino\libraries\TFT_eSPI/TFT_eSPI.h:368:25: error: 'TFT_WIDTH' was not declared in this scope
   TFT_eSPI(int16_t _W = TFT_WIDTH, int16_t _H = TFT_HEIGHT);
                         ^
C:\Users\user\Documents\Arduino\libraries\TFT_eSPI/TFT_eSPI.h:368:49: error: 'TFT_HEIGHT' was not declared in this scope
   TFT_eSPI(int16_t _W = TFT_WIDTH, int16_t _H = TFT_HEIGHT);
                                                 ^
In file included from C:\Users\user\Documents\Arduino\ESP32-WROVER_Web_Radio\ESP32-WROVER_Web_Radio.ino:2:0:
main.h:211:25: error: call to 'TFT_eSPI::TFT_eSPI(int16_t, int16_t)' uses the default argument for parameter 1, which is not yet defined
 TFT_eSPI tft = TFT_eSPI();  
                         ^
main.h:211:25: error: call to 'TFT_eSPI::TFT_eSPI(int16_t, int16_t)' uses the default argument for parameter 2, which is not yet defined
In file included from C:\Users\user\Documents\Arduino\ESP32-WROVER_Web_Radio\ESP32-WROVER_Web_Radio.ino:3:0:
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'void initDisplay()':
tftHelpers.h:78:9: error: 'class TFT_eSPI' has no member named 'setTouch'
     tft.setTouch(calData);
         ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'void setupDisplayModule(bool)':
tftHelpers.h:151:19: error: 'FreeSansBold12pt7b' was not declared in this scope
  tft.setFreeFont(&FreeSansBold12pt7b);
                   ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'void drawStnChangeButton()':
tftHelpers.h:304:19: error: 'FreeSansBold12pt7b' was not declared in this scope
  tft.setFreeFont(&FreeSansBold12pt7b);
                   ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'void drawPlusButton(bool)':
tftHelpers.h:351:19: error: 'FreeSansBold12pt7b' was not declared in this scope
  tft.setFreeFont(&FreeSansBold12pt7b);
                   ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'void drawMinusButton(bool)':
tftHelpers.h:357:19: error: 'FreeSansBold12pt7b' was not declared in this scope
  tft.setFreeFont(&FreeSansBold12pt7b);
                   ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'void drawBufferLevel(size_t, bool)':
tftHelpers.h:423:21: error: 'FreeSans9pt7b' was not declared in this scope
    tft.setFreeFont(&FreeSans9pt7b);
                     ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'bool getStnChangeButtonPress()':
tftHelpers.h:436:24: error: 'class TFT_eSPI' has no member named 'getTouch'
  boolean pressed = tft.getTouch(&t_x, &t_y, 50);
                        ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'void getPlusButtonPress()':
tftHelpers.h:472:25: error: 'class TFT_eSPI' has no member named 'getTouch'
   boolean pressed = tft.getTouch(&t_x, &t_y);
                         ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'void getMinusButtonPress()':
tftHelpers.h:548:25: error: 'class TFT_eSPI' has no member named 'getTouch'
   boolean pressed = tft.getTouch(&t_x, &t_y);
                         ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'void getSpkrButtonPress()':
tftHelpers.h:624:25: error: 'class TFT_eSPI' has no member named 'getTouch'
   boolean pressed = tft.getTouch(&t_x, &t_y, 20);
                         ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'void getBulbButtonPress()':
tftHelpers.h:714:25: error: 'class TFT_eSPI' has no member named 'getTouch'
   boolean pressed = tft.getTouch(&t_x, &t_y, 50);
                         ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'void displayStationName(std::__cxx11::string)':
tftHelpers.h:755:19: error: 'FreeSansOblique12pt7b' was not declared in this scope
  tft.setFreeFont(&FreeSansOblique12pt7b);
                   ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'void displayTrackArtist(std::__cxx11::string)':
tftHelpers.h:819:19: error: 'FreeSans9pt7b' was not declared in this scope
  tft.setFreeFont(&FreeSans9pt7b);
                   ^
tftHelpers.h:830:20: error: 'FreeSans12pt7b' was not declared in this scope
   tft.setFreeFont(&FreeSans12pt7b);
                    ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\tftHelpers.h: In function 'void drawDummyPlusMinusButtons()':
tftHelpers.h:844:19: error: 'FreeSansBold12pt7b' was not declared in this scope
  tft.setFreeFont(&FreeSansBold12pt7b);
                   ^
In file included from C:\Users\user\Documents\Arduino\ESP32-WROVER_Web_Radio\ESP32-WROVER_Web_Radio.ino:6:0:
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\stationSelectHelper.h: In function 'void listStationsOnScreen(int)':
stationSelectHelper.h:147:20: error: 'FreeSans9pt7b' was not declared in this scope
   tft.setFreeFont(&FreeSans9pt7b);
                    ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\stationSelectHelper.h: In function 'void drawNextStationBtn(bool)':
stationSelectHelper.h:180:19: error: 'FreeSans9pt7b' was not declared in this scope
  tft.setFreeFont(&FreeSans9pt7b);
                   ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\stationSelectHelper.h: In function 'void drawPrevStationBtn(bool)':
stationSelectHelper.h:196:19: error: 'FreeSans9pt7b' was not declared in this scope
  tft.setFreeFont(&FreeSans9pt7b);
                   ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\stationSelectHelper.h: In function 'void drawStationCancelButton()':
stationSelectHelper.h:212:19: error: 'FreeSansBold9pt7b' was not declared in this scope
  tft.setFreeFont(&FreeSansBold9pt7b);
                   ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\stationSelectHelper.h: In function 'void stationNextPrevButtonPressed()':
stationSelectHelper.h:233:22: error: 'class TFT_eSPI' has no member named 'getTouch'
   bool pressed = tft.getTouch(&x, &y, 30);
                      ^
C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\stationSelectHelper.h: In function 'int getStationListPress()':
stationSelectHelper.h:314:22: error: 'class TFT_eSPI' has no member named 'getTouch'
   bool pressed = tft.getTouch(&x, &y, 30);
                      ^
C:\Users\user\Documents\Arduino\ESP32-WROVER_Web_Radio\ESP32-WROVER_Web_Radio.ino: In function 'void setup()':
ESP32-WROVER_Web_Radio:80:24: error: could not convert 'player.VS1053::begin()' from 'void' to 'bool'
  } while (!player.begin() && mp3StartCount > 0);
                        ^
ESP32-WROVER_Web_Radio:80:25: error: in argument to unary !
  } while (!player.begin() && mp3StartCount > 0);
                         ^
ESP32-WROVER_Web_Radio:115:25: error: invalid conversion from 'uint16_t {aka short unsigned int}' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
  player.setTone(SCI_BASS);
                         ^
In file included from C:\Users\user\AppData\Local\Temp\arduino_build_369445\sketch\main.h:29:0,
                 from C:\Users\user\Documents\Arduino\ESP32-WROVER_Web_Radio\ESP32-WROVER_Web_Radio.ino:2:
C:\Users\user\Documents\Arduino\libraries\ESP_VS1053_Library-master\src/VS1053.h:136:10: note:   initializing argument 1 of 'void VS1053::setTone(uint8_t*)'
     void setTone(uint8_t *rtone);
          ^
ESP32-WROVER_Web_Radio:208:16: error: 'TFT_BL' was not declared in this scope
  ledcAttachPin(TFT_BL, 0);

**Comment by RalphBacon** [comment]
The problem lies with the TFT_eSPI-2.2.23 library - I can only assume you are using a different version. Use the one I included in the libraries folder (205-Internet-Radio/Arduino IDE Version/ESP32-WROVER_Web_Radio/libraries/) in the GitHub and ensure you do not have any other libraries that might be picked up by the Arduino IDE instead of this one.
